home:
    path: /
    controller: App\Controller\HomeController::indexAction

about:
    path: /about
    controller: App\Controller\AboutController::indexAction

contact:
    path: /contact
    controller: App\Controller\ContactController::indexAction

contact_send:
    path: /contact_send
    controller: App\Controller\ContactController::sendAction
    methods: POST